### ISSUE TITLE
Is it possible to build only a specific entry point?

### ISSUE THREAD

**Issue by leojh** [Derek-Hu/react-app-rewire-multiple-entry#13]
First of all, this is a great package thank you all for maintaining this.

We're wanting to perhaps only build a specific entry point and not all... is this something that someone else has come across?

**Comment by Derek-Hu** [comment]
Do you mean build partial entries, for example 3 entires when you have 5 entries. You can enable/disable, comment some entries manually or pass parameters in npm scripts to dynamic enable/disable entries.

**Comment by leojh** [comment]
Yeap this works. Just making sure there isn’t a native way of doing this through webpack or another method.
