### ISSUE TITLE
Embeddable react widget

### ISSUE THREAD

**Issue by neuralsea-lab** [Derek-Hu/react-app-rewire-multiple-entry#14]
Thank you for making this available. Is it possible to honour the full webpack schema?
e.g. https://github.com/seriousben/embeddable-react-widget/blob/master/webpack.config.js

**Comment by Derek-Hu** [comment]
I think you may achieve the purpose via multiple `webpack.config.js`, one of `libraryExport ` and another for application `publicPath `. 

Moreover, I'm afraid that there is little possibility that too many common configuration between those `webpack ` config files.

I think it's better to seperate the library codes with application codes.

This original intention of `react-app-rewire-multiple-entry` generate html entry.
