### ISSUE TITLE
Disable Main Entry During Build?

### ISSUE THREAD

**Issue by McSqueakins** [Derek-Hu/react-app-rewire-multiple-entry#15]
Just wondering if there is a way to disable the main entry point during the build process? As in, I have my main application and then in config-overrides.js I've defined a separate app/entry point for login... Is it possible to only build the login app? Thanks for the assistance :)

**Comment by Derek-Hu** [comment]
You can add below code after plugin `
react-app-rewire-multiple-entry`  in file `config-overrides.js` to disable the main entry point:
```
delete config.entry.main;
```

```
const multipleEntry = require('react-app-rewire-multiple-entry')([{
    entry: 'src/entry/landing.js',
    template: 'public/landing.html',
    outPath: '/landing.html'
}]);

module.exports = {
  webpack: function(config) {
    multipleEntry.addMultiEntry(config);

    delete config.entry.main;

    return config;
  }
};

```

or using with `customize-cra`

```
const multipleEntry = require('react-app-rewire-multiple-entry')([
  {
    entry: 'src/entry/landing.js',
    template: 'public/landing.html',
    outPath: '/landing.html'
  }
]);

const {
  // addBundleVisualizer,
  override,
  overrideDevServer
} = require('customize-cra');

module.exports = {
  webpack: override(
    multipleEntry.addMultiEntry
    // addBundleVisualizer()
    config => {
        delete config.entry.main;
    }
  ),
};
```

Actually, entry points are added in webpack config entry in format `[name].[hash]`,  apply below configurations:
  ```
[{
    entry: 'src/entry/landing.js',
    template: 'public/landing.html',
    outPath: '/landing.html'
  },  {
    entry: 'src/entry/login.js',
    outPath: '/login.html'
  }]
```
webpack config entry looks like: 
```
{
  main: [...],
  'landing.dc1d8246': [...],
  'login.5a3f2acd': [...],
}
``` 
if you want to only build the login app, you can delete all entries except the entry name start with `login`.

Thanks a lot!

**Comment by McSqueakins** [comment]
Great, thanks!!

**Comment by McSqueakins** [comment]
So tried doing this, and while I can see that the main entrypoint is definitely getting deleted from the config.entry object, the application will not build when the main entrypoint is deleted. I'll keep playing around with it. Thanks for the help, though!

**Comment by McSqueakins** [comment]
for anyone trying to do this and running into the same issue, solution is here: https://github.com/timarney/react-app-rewired/issues/421
