### ISSUE TITLE
Cannot set properties of undefined (setting 'chunks')

### ISSUE THREAD

**Issue by MarcelPawlo** [Derek-Hu/react-app-rewire-multiple-entry#33]
Hi

when I set an valid entry (existing file) in config-overrides.js I get the error "Cannot set properties of undefined (setting 'chunks')" and cannot start or build. Without the entry (empty object/array) everything works.

`const multipleEntry = require('react-app-rewire-multiple-entry')([
    {
        entry: 'src/index.js',
    }
  ]);
  
  module.exports = {
    webpack: function(config, env) {
      multipleEntry.addMultiEntry(config);
      return config;
    }
  };`

**Comment by MarcelPawlo** [comment]
Seems to be a problem with Webpack 5 because defaultEntryHTMLPlugin.options.chunks is not accessible.

**Comment by zur4ik** [comment]
Have got the same error. Is there any workaround at the moment?

**Comment by panlina** [comment]
Same here.

**Comment by Derek-Hu** [comment]
Issue fixed in v2.2.2. Thanks!
