### ISSUE TITLE
index.js will always in other entry

### ISSUE THREAD

**Issue by lyc-chengzi** [Derek-Hu/react-app-rewire-multiple-entry#8]
if I add a entry like this:
`const multipleEntry = require('react-app-rewire-multiple-entry')([

{

        entry: 'src/entry/bindex.tsx',
        template: 'public/cappindex.html',
        outPath: '/react/capp/index.html'
}
]);`

after build, I can see /react/capp/index.html contains:

!*** multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./src/index.tsx ./src/entry/bindex.tsx ***!

__webpack_require__(/*! D:\project\node_modules\react-dev-utils\webpackHotDevClient.js */"./node_modules/react-dev-utils/webpackHotDevClient.js");
__webpack_require__(/*! D:\project\**src\index.tsx** */"./src/index.tsx");
module.exports = __webpack_require__(/*! D:\project\src\entry\bindex.tsx */"./src/entry/bindex.tsx");

index.tsx is the default entry for create-react-app

### `but I just need bindex.tsx`

Can someone help me？

**Comment by Derek-Hu** [comment]
Which version do you use?

**Comment by Derek-Hu** [comment]
Cannot reproduce using v2.x, Could you give an example?

**Comment by Derek-Hu** [comment]
It works in sample: https://github.com/Derek-Hu/cra-ts-multiple-entry/tree/v1.0.0

**Comment by lyc-chengzi** [comment]
`const { override, fixBabelImports, addLessLoader, useEslintRc } = require('customize-cra');
const multipleEntry = require('react-app-rewire-multiple-entry')([
    /*browserHistory页面*/
    {
        entry: 'src/entry/bindex.tsx',
        template: 'public/cappindex.html',
        outPath: '/react/capp/index.html'
    },
    /*hashHistory页面*/
    {
        entry: 'src/entry/aindex.tsx',
        template: 'public/index.html',
        outPath: '/index.html'
    }
]);

module.exports = override(
    multipleEntry.addMultiEntry,
    useEslintRc(),
    fixBabelImports('import-andtd-mobile', {
        libraryName: 'antd-mobile',
        libraryDirectory: 'es',
        style: 'css',
    }),
    addLessLoader({
        javascriptEnabled: true,
        modifyVars: {'@primary-color': '#1DA57A'},
    })
);`


this is my config-overrides.js file.

and version is 
"react-app-rewire-multiple-entry": "^2.1.0"
"react-app-rewired": "^2.1.3"
"customize-cra": "^0.2.12",

**Comment by lyc-chengzi** [comment]
yesterday I use react-app-rewire-multiple-entry 2.0.1, now update to 2.1.0 have already been solved
